@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Работает с платёжным приложением через веб или мобильный интерфейс")

System(observability, "Наблюдаемость", "Grafana stack")

System_Boundary(paymentSystem, "Платёжная система") {
    Container(individuals_api, "Individuals Api", "Java, Spring Boot WebFlux", "Оркестратор: регистрация, логин, обновление токена, получение данных пользователя")
    Container(keycloak, "Keycloak", "Keycloak", "Управление пользователями, токены, роли, авторизация")
    ContainerDb(keycloak_database, "Keycloak Database", "PostgreSQL", "Хранение учетных данных пользователей Keycloak")
    Container(persons_service, "Persons Service", "Java, Spring Boot", "Управления пользователями и их связанными сущностями")
    ContainerDb(person_database, "Person Database", "PostgreSQL", "Хранение информации по профилям пользователей")
}

Rel(observability, paymentSystem, "Собирает метрики, логи и трейсы", "OTLP gRPC, HTTP, Wire Protocol")

Rel(user, individuals_api, "Регистрируется, просматривает профиль, совершает транзакции", "HTTP")
Rel(individuals_api, keycloak, "Создание пользователя и хранение учетных данных", "HTTP")
Rel(keycloak, keycloak_database, "Запись / чтение данных", "SQL")
Rel(individuals_api, persons_service, "Заполнение профиля пользователя", "HTTP")
Rel(persons_service, person_database, "Запись / чтение данных", "SQL")


@enduml