@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Работает с платёжным приложением через веб или мобильный интерфейс")

System(observability, "Наблюдаемость", "Grafana stack")

System_Boundary(paymentSystem, "Платёжная система") {
    Container(individuals_api, "Individuals Api", "Java, Spring Boot WebFlux", "Оркестратор: регистрация, логин, обновление токена, получение данных пользователя")
    Container(keycloak, "Keycloak", "Keycloak", "Управление пользователями, токены, роли, авторизация")
    ContainerDb(keycloak_database, "Keycloak Database", "PostgreSQL", "Хранение учетных данных пользователей Keycloak")
    Container(persons_service, "Persons Service", "Java, Spring Boot", "Управления пользователями и их связанными сущностями")
    ContainerDb(person_database, "Person Database", "PostgreSQL", "Хранение информации по профилям пользователей")

    Container(wallet_service, "Wallet Service", "Java, Spring Boot", "Управление кошельками пользователей, хранение/создание транзакций")
    ContainerDb(wallet_database, "Wallet Database", "PostgreSQL", "Хранение информации о пользовательских кашельках и транзакциям")
    Container(kafka, "Kafka", "Kafka", "Асинхронный обмен информации между микросервисами")
}

Rel(observability, paymentSystem, "Собирает метрики, логи и трейсы", "OTLP gRPC, HTTP, Wire Protocol")

Rel(user, individuals_api, "Регистрируется, просматривает профиль, совершает транзакции", "HTTP")
Rel(individuals_api, keycloak, "Создание пользователя и хранение учетных данных", "HTTP")
Rel(keycloak, keycloak_database, "Запись / чтение данных", "SQL")
Rel(individuals_api, persons_service, "Заполнение профиля пользователя", "HTTP")
Rel(persons_service, person_database, "Запись / чтение данных", "SQL")

Rel(individuals_api, wallet_service, "Создание кошельков, транзакций на ввод, вывод и трансфер средств", "HTTP")
Rel(wallet_service, wallet_database, "Запись / чтение данных", "SQL")
Rel(wallet_service, kafka, "Отправка и получение событийных сообщений по транзакциям пополнения и вывода средств с кошелька.")


Person(dev, "Разработчик / DevOps", "Следит за состоянием системы")

System_Boundary(observability, "Наблюдаемость") {
    Container(alloy, "Alloy", "Grafana Alloy", "Собирает и маршрутизирует телеметрию")
    Container(prometheus, "Prometheus", "Prometheus", "Хранит метрики")
    Container(loki, "Loki", "Grafana Loki", "Хранит логи")
    Container(tempo, "Tempo", "Grafana Tempo", "Хранит трейсы")
    Container(grafana, "Grafana", "Grafana", "Визуализация метрик, логов и трейсов")
}

Rel(dev, grafana, "Смотрит дашборды и алерты", "HTTP")

Rel(alloy, prometheus, "Пишет метрики", "remote_write HTTP")
Rel(alloy, loki, "Пишет логи", "HTTP")
Rel(alloy, tempo, "Пишет трейсы", "OTLP gRPC")

Rel(grafana, prometheus, "Читает метрики", "PromQL")
Rel(grafana, loki, "Читает логи", "LogQL")
Rel(grafana, tempo, "Читает трейсы", "Tempo HTTP API")



@enduml