@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(dev, "Разработчик / DevOps", "Следит за состоянием системы")

System_Boundary(observability, "Наблюдаемость") {
    Container(alloy, "Alloy", "Grafana Alloy", "Собирает и маршрутизирует телеметрию")
    Container(prometheus, "Prometheus", "Prometheus", "Хранит метрики")
    Container(loki, "Loki", "Grafana Loki", "Хранит логи")
    Container(tempo, "Tempo", "Grafana Tempo", "Хранит трейсы")
    Container(grafana, "Grafana", "Grafana", "Визуализация метрик, логов и трейсов")
}

System_Boundary(paymentSystem, "Платёжная система") {
    Container(individuals_api, "Individuals Api", "Java, Spring Boot WebFlux", "Оркестратор: регистрация, логин, обновление токена, получение данных пользователя")
    Container(keycloak, "Keycloak", "Keycloak", "Управление пользователями, токены, роли, авторизация")
    ContainerDb(keycloak_database, "Keycloak Database", "PostgreSQL", "Хранение учетных данных пользователей Keycloak")
    Container(persons_service, "Persons Service", "Java, Spring Boot", "Управления пользователями и их связанными сущностями")
    ContainerDb(person_database, "Person Database", "PostgreSQL", "Хранение информации по профилям пользователей")
}

Rel(dev, grafana, "Смотрит дашборды и алерты", "HTTP")

Rel(alloy, prometheus, "Пишет метрики", "remote_write HTTP")
Rel(alloy, loki, "Пишет логи", "HTTP")
Rel(alloy, tempo, "Пишет трейсы", "OTLP gRPC")

Rel(grafana, prometheus, "Читает метрики", "PromQL")
Rel(grafana, loki, "Читает логи", "LogQL")
Rel(grafana, tempo, "Читает трейсы", "Tempo HTTP API")

Rel(alloy, individuals_api, "Забирает метрики", "HTTP scrape /actuator/prometheus")
Rel(individuals_api, alloy, "Отправляет трейсы", "OTLP gRPC")

Rel(alloy, persons_service, "Забирает метрики", "HTTP scrape /actuator/prometheus")
Rel(persons_service, alloy, "Отправляет трейсы", "OTLP gRPC")
Rel(alloy, person_database, "Забирает метрики", "Wire Protocol")

Rel(alloy, keycloak, "Забирает метрики", "HTTP scrape /metrics")
Rel(alloy, keycloak_database, "Забирает метрики", "Wire Protocol")


@enduml