spring:
  application:
    name: person-service-api

  main:
    banner-mode: off

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30_000
      max-lifetime: 1_800_000
      pool-name: person-service-hikari-pool

  flyway:
    locations: classpath:db/migration
    default-schema: person

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
        exclude: env, beans

  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
    enable:
      http: true

  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_TRACING_GRPC_ENDPOINT:http://localhost:4317}
          transport: grpc
  logging:
    export:
      otlp:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false