@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(person_service, "Person Service") {

    Component(individualController, "IndividualController", "REST Controller", "Обрабатывает HTTP-запросы /individuals")

    Component(individualService, "IndividualService", "Service", "Оркестрирует все операции над профилем физ. лица:\nсоздание, обновление, смена статуса, удаление.\nВключает логику работы с User и Address")

    Component(individualMapper, "IndividualMapper", "MapStruct", "Маппинг между Entity и DTO")

    Component(individualRepository, "IndividualRepository", "Spring Data JPA", "CRUD операции над INDIVIDUALS.\nCascade сохраняет USER и ADDRESS")

    Component(countryRepository, "CountryRepository", "Spring Data JPA", "Поиск страны по alpha2/alpha3")

    Component(audit, "Audit", "Hibernate Envers", "Автоматический аудит изменений\nINDIVIDUALS, USERS, ADDRESSES")
}

Container(individuals_api, "Individuals API", "Java, Spring Boot WebFlux", "Оркестратор")
ContainerDb(person_db, "Person Database", "PostgreSQL", "Хранение профилей пользователей")

Rel(individuals_api, individualController, "REST API", "HTTP/JSON")

Rel(individualController, individualMapper, "Маппинг request → entity")
Rel(individualController, individualService, "Вызов бизнес-операций")
Rel(individualService, individualMapper, "Маппинг entity → response")

Rel(individualService, individualRepository, "Сохранение / чтение Individual")
Rel(individualService, countryRepository, "Поиск страны по alpha2")

Rel(individualRepository, person_db, "SQL", "JDBC")
Rel(countryRepository, person_db, "SQL", "JDBC")
Rel(audit, person_db, "Запись истории изменений", "SQL")

@enduml