@startuml

autonumber

actor Client as client
participant "Individuals API" as api
participant Keycloak as keycloak


client -> api: POST \n /v1/auth/refresh-token \n application/json
api -> keycloak: POST \n /realms/{realm}/protocol/openid-connect/token \n application/x-www-form-urlencoded \n grant_type: refresh_token
keycloak -> keycloak: Обновление JWT токена по refresh_token
keycloak --> api: application/json \n access_token, refresh_token ...
api --> client: application/json \n access_token, refresh_token ...

alt #FFCCCC Неверный refresh_token
keycloak --> api: status: 400 \n application/json \n invalid_grant ...
api -> api: Обработка ошибки
api --> client: status: 401 \n application/json \n error, status
end

@enduml