@startuml

autonumber

actor Client as client
participant "Individuals API" as api
participant "Person Service" as person
participant "Person Database" as personDb

client -> api: PATCH \n Authorization: Bearer ... \n application\json \n /v1/users/{userId}/individual
api -> api: Валидация токена

alt #FFCCCC Ошибка валидации токена
api -> api: Валидация Bearer токена
api --> client: status: 401 \n application\json \n error, status
end

api -> person: PATCH \n Authorization: Bearer {service_token} \n application\json \n /v1/users/{userId}/individual
person -> personDb: обновление данных профиля
personDb --> person: подтверждение обновления
person --> api: status: 200 \n application/json \n {...}
api --> client: status: 200 \n application/json \n {...}
@enduml