keycloak:
  url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:payment-system}
  client-id: ${KEYCLOAK_CLIENT_ID:individuals-api}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

  admin-token:
    ttl-seconds: ${KEYCLOAK_ADMIN_TOKEN_TTL_SECONDS:300}
    refresh-margin-seconds: ${KEYCLOAK_ADMIN_TOKEN_REFRESH_MARGIN_SECONDS:60}

  requests-retry:
    attempts: ${KEYCLOAK_REQUESTS_RETRY_ATTEMPTS:3}
    delay-seconds: ${KEYCLOAK_REQUESTS_DELAY_SECONDS:1}
    request-timeout-seconds: ${KEYCLOAK_REQUESTS_TIMEOUT_SECONDS:10}

spring:
  http:
    serviceclient:
      person-service:
        base-url: ${PERSON_SERVICE_URL:http://localhost:8083}/v1

  main:
    banner-mode: off

  application:
    name: individuals-api

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            authorization-grant-type: password
        provider:
          keycloak:
            token-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

resilience4j:
  circuitbreaker:
    sliding-window-size: 10
    failure-rate-threshold: 50
    slow-call-rate-threshold: 80
    slow-call-duration-threshold-seconds: 3
    wait-duration-in-open-state-seconds: 10
    permitted-calls-in-half-open-state: 3
  bulkhead:
    max-concurrent-calls: 20
    max-wait-duration-ms: 0

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
        exclude: env, beans

  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
    enable:
      http: true

  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_TRACING_GRPC_ENDPOINT:http://localhost:4317}
          transport: grpc
  logging:
    export:
      otlp:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false